### ISSUE TITLE
hash test errors

### ISSUE THREAD

**Issue by barthch** [EthanGriffee/Ethan-and-Divit-Part-2-Software-Dev#13]
https://github.com/EthanGriffee/Ethan-and-Divit-Part-2-Software-Dev/blob/81c62fe623d591e92b94eba0cf3e1adece12a765/test-array.cpp#L97

It is not standard to compare hashes across different objects

https://github.com/EthanGriffee/Ethan-and-Divit-Part-2-Software-Dev/blob/81c62fe623d591e92b94eba0cf3e1adece12a765/test-array.cpp#L99

This specifies the implementation.

**Comment by EthanGriffee** [comment]
So there shouldn't be tests for hash?

**Comment by barthch** [comment]
There should be tests of hash. You should test how hash operates. i.e. the hash of an object should be equal to the hash of the same object. If two strings are equal they should also have the same hash.

That is what should be tested.

**Comment by barthch** [comment]
closing because it is similar to #20
