### ISSUE TITLE
Float comparison

### ISSUE THREAD

**Issue by barthch** [EthanGriffee/Ethan-and-Divit-Part-2-Software-Dev#15]
https://github.com/EthanGriffee/Ethan-and-Divit-Part-2-Software-Dev/blob/81c62fe623d591e92b94eba0cf3e1adece12a765/test-array.cpp#L152

Since float primitives are not stored as exact values it is impossible to compare floats with '=='.
This can be done with the FloatObj equals function, or by defining a acceptable range for floating point error.

**Comment by EthanGriffee** [comment]
Ok I added a comparison.
