### ISSUE TITLE
String length

### ISSUE THREAD

**Issue by barthch** [EthanGriffee/Ethan-and-Divit-Part-2-Software-Dev#17]
We have two other groups who specify String->size() to be the way to get the length of the string. Can you change it

**Comment by EthanGriffee** [comment]
#4 asks me to use the way outlined in class (using length()) if @az0977776 agrees I can change it to size(), or I can use a different method to confirm that the expected string is there?

**Comment by canonsawrey** [comment]
Would you be opposed to using the standard string and object libraries mentioned on Piazza? 
Piazza: https://piazza.com/class/k51bluky59n2jr?cid=345
Repo: https://github.com/chasebish/cwc_object_string
I'd be happy to open a PR importing those classes as a submodule

**Comment by EthanGriffee** [comment]
I didn't really need to use string length so, I just removed it

**Comment by barthch** [comment]
However length() is still in your spec for String. Could you remove it?

**Comment by EthanGriffee** [comment]
I can change it but shouldn't it not matter since you don't have to use my String spec?

**Comment by barthch** [comment]
All good
