### ISSUE TITLE
indexOf return type

### ISSUE THREAD

**Issue by barthch** [EthanGriffee/Ethan-and-Divit-Part-2-Software-Dev#18]
https://github.com/EthanGriffee/Ethan-and-Divit-Part-2-Software-Dev/blob/23eb21b69e7c7869213e3c9fc054beb772571e6a/array.h#L43-L44

If the object does not exist then how can it return -1 if the return type is size_t?
Is it possible to return any number greater than size() of the array?

**Comment by EthanGriffee** [comment]
Thanks, I will change the return to int.
