### ISSUE TITLE
Hash fucnction

### ISSUE THREAD

**Issue by canonsawrey** [EthanGriffee/Ethan-and-Divit-Part-2-Software-Dev#20]
https://github.com/EthanGriffee/Ethan-and-Divit-Part-2-Software-Dev/blob/23eb21b69e7c7869213e3c9fc054beb772571e6a/test-array.cpp#L112

Not sure about this test. It implies that the hash of an array should be the sum of its elements. This has poor implications that a string's hash is equivalent to a 1 element array containing that string. Also 2 arrays containing the same elements in different orders will hash the same.

**Comment by EthanGriffee** [comment]
Ok, changed the hashing tests to not rely on that.
