### ISSUE TITLE
indexof signature

### ISSUE THREAD

**Issue by az0977776** [EthanGriffee/Ethan-and-Divit-Part-2-Software-Dev#21]
`virtual int indexOf(Object* obj)`
`virtual int indexOf(Object* obj, size_t i)`

`virtual void set(size_t i, Object* obj)`

the signature of set implies that you can have up to size_t items in the array.
what if the index of the object is greater than the max int

**Comment by EthanGriffee** [comment]
That is a good point but if I cannot think of any datatype pair that would not have this or a similar issue assuming we want i to be non negative, because if the return type of indexof and i were the same datatype, then there would be no way to know if indexof is returning a "not found" if the array is at maximum capacity.

**Comment by az0977776** [comment]
what if you have it return a value > length of the array if it is not found? The user can then check against the size to see if it exists or not.

**Comment by EthanGriffee** [comment]
But doesn't that lead to a similar problem? if the size of the array is at the max allowed, then indexof would not be able to return a value > the size of the array.

**Comment by az0977776** [comment]
yes, but size_t's max value is a lot higher than int and even though both size_t and int can run into that indexOf problem when the size is max, size_t will make more sense in your array object as it matches the signature of the other functions.

**Comment by az0977776** [comment]
bump

**Comment by EthanGriffee** [comment]
We did not think it was worth the confusion of having to check the size after using indexOf. We believe that if you want to have an array with more than 2,147,483,647 items it would be better to design specifically around it being that large of an array.

**Comment by az0977776** [comment]
but you use size_t for index in all your other functions

**Comment by EthanGriffee** [comment]
Yes, because that is what we have been using for an unsigned number in class. I do not believe there is a datatype that I can use that values range from 0 to 2,147,483,647.

**Comment by az0977776** [comment]
I still think that the type for indices should be consistent throughout your specification (size_t) and that checking if the return value of indexOf > size() is the same complexity as check if the return value is -1. However, at this point, we are going to use the current commit hash of your spec and I am going to close this issue.
