### ISSUE TITLE
Test case fixes

### ISSUE THREAD

**Issue by trevorstenson** [EthanGriffee/Ethan-and-Divit-Part-2-Software-Dev#22]
On line 27 of test-array.cpp, ```CS4500_ASSERT_TRUE(a->size() == 2)``` should actually be checking size is equal to 3, not 2.

In test ```push_set_float_array_test``` on line 195, float x should be renamed to something else as float x is initialized previously. Additionally, on line 193 where it says:```CS4500_ASSERT_TRUE( x < epsilon && x > epsilon)``` how can x be both greater than and less than epsilon? Please look into this test as a whole.

**Comment by EthanGriffee** [comment]
Yeah sorry, I thought I had made that size change before. Changed x > epsilon to x > -epsilon.
