### ISSUE TITLE
concat StringArray with IntArray

### ISSUE THREAD

**Issue by barthch** [EthanGriffee/Ethan-and-Divit-Part-2-Software-Dev#23]
what should happen? I assume exit with error code 1.

**Comment by EthanGriffee** [comment]
Since concat returns a new array, I think it should be fine to concat a StringArray with an IntArray. However, I do think that concating two StringArrays should return a StringArray, so I will make changes/ tests to reflect that.

**Comment by barthch** [comment]
I am confused. It **_should_** be fine to concat StringArray with and IntArray or _**should not**_? If so what object should be returned?

**Comment by EthanGriffee** [comment]
It should be fine as an array should be returned if StringArray is concat with IntArray, since concat does not modify the array it is called on and only returns a new array.

**Comment by EthanGriffee** [comment]
> However, I do think that concating two StringArrays should return a StringArray, so I will make changes/ tests to reflect that.

Nevermind I could not think of a good way to do this

**Comment by barthch** [comment]
So for concat of a StringArray with an IntArray an new Array should be returned with all objects concated togther. i.e. 
x = stringArray->concat(intArray); 
x->push(new Object());
 
Please give examples!

**Comment by EthanGriffee** [comment]
Ok I added a test for that
