### ISSUE TITLE
exception in CwC

### ISSUE THREAD

**Issue by barthch** [EthanGriffee/Ethan-and-Divit-Part-2-Software-Dev#24]
For all your comments you say "throw an exception" however exception do not exist in CwC. Tests indicate that you mean "exit with error code 1". Is this correct?

**Comment by EthanGriffee** [comment]
Yeah, I thought he had called them exceptions in a piazza post I thought, but it looks like old posts are deleted, and saying exit with code 1 makes more sense so I will change it.
