### ISSUE TITLE
standardize object and string

### ISSUE THREAD

**Issue by az0977776** [EthanGriffee/Ethan-and-Divit-Part-2-Software-Dev#4]
Can we try to just use the definitions of string and object that Jan provided us:
https://piazza.com/class/k51bluky59n2jr?cid=330

https://piazza.com/class/k51bluky59n2jr?cid=166

**Comment by EthanGriffee** [comment]
I don't see why that wouldn't work, the only method we call on Object or String is hash() which is included in that definition.
