### ISSUE TITLE
Memory Leaks

### ISSUE THREAD

**Issue by barthch** [EthanGriffee/Ethan-and-Divit-Part-2-Software-Dev#5]
Test.cpp does not have and delete statements. Who owns the objects that are added or set in the Array. Should we copy the Objects that are passed in? (Object would need a copy method to make this work)

Also, for get, who owns the returned Object?

**Comment by EthanGriffee** [comment]
I did not have delete statements because test.cpp in HW02 did not contain them. I added them, we did not intend for the Array to own the Objects.

**Comment by barthch** [comment]
Looks good thanks.
