### ISSUE TITLE
Test hash

### ISSUE THREAD

**Issue by barthch** [EthanGriffee/Ethan-and-Divit-Part-2-Software-Dev#6]
https://github.com/EthanGriffee/Ethan-and-Divit-Part-2-Software-Dev/blob/4d3c02a47d4afdb68d8cde32c440d74b2e2c1503/test-array.cpp#L79

You specify the actual hash of a String. This forces us to implement hash in a specific way.

**Comment by EthanGriffee** [comment]
Changed the hash testing of array to be independent from the implementation of hash() in string.
