### ISSUE TITLE
Array of int, bool, float, and String

### ISSUE THREAD

**Issue by barthch** [EthanGriffee/Ethan-and-Divit-Part-2-Software-Dev#8]
As per [this post](https://piazza.com/class/k51bluky59n2jr?cid=320) and [this post](https://piazza.com/class/k51bluky59n2jr?cid=331) array has to handle int, bool, float, and String.

Please add tests demonstrating how this will be handled.

**Comment by EthanGriffee** [comment]
added implementation using wrappers
